name: deployTestPipeline2

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Package
        run: mvn -B clean package -DskipTests
  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose up -d